quarkus:
  http:
    host: 0.0.0.0
    port: 8082

  rest-client:
    consumer-api:
      url: http://localhost:8081

greeting:
  message: "hello"



smallrye:
  jwt:
    sign:
      key:
        location: src/main/local/privateKey.pem
